-- Insertar Roles iniciales
INSERT INTO "Roles" ("id", "name", "description", "created_at", "updated_at")
VALUES (
  gen_random_uuid()::text,
  'Administrador',
  'Rol con acceso total al sistema',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
)
ON CONFLICT ("name") DO NOTHING;

INSERT INTO "Roles" ("id", "name", "description", "created_at", "updated_at")
VALUES (
  gen_random_uuid()::text,
  'Cliente', 
  'Rol Basico', 
  CURRENT_TIMESTAMP, 
  CURRENT_TIMESTAMP
)
ON CONFLICT ("name") DO NOTHING;

-- Seed root admin user
INSERT INTO "Users" (
  "id",
  "email",
  "password",
  "firstName",
  "lastName",
  "active",
  "email_verified",
  "created_at",
  "updated_at",
  "roleId"
)
VALUES (
  gen_random_uuid()::text,
  'root@admin.com',
  '$2b$10$iKVYW7.KvqA0hyC5nSa48.3WOBQn7BrkNYC3DgsiNknuymFaKAAY2',
  'Root',
  'Admin',
  true,
  true,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP,
  (SELECT id FROM "Roles" WHERE "name" = 'Administrador' LIMIT 1)
)
ON CONFLICT ("email") DO NOTHING;

-- Seed 50 sample client users
INSERT INTO "Users" (
  "id",
  "email",
  "password",
  "firstName",
  "lastName",
  "active",
  "email_verified",
  "created_at",
  "updated_at",
  "roleId"
) VALUES
  (
    gen_random_uuid()::text,
    'jose.salazar1@hotmail.com',
    '$2b$10$iKVYW7.KvqA0hyC5nSa48.3WOBQn7BrkNYC3DgsiNknuymFaKAAY2',
    'José',
    'Salazar',
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    (SELECT id FROM "Roles" WHERE "name" = 'Cliente' LIMIT 1)
  ),
  (
    gen_random_uuid()::text,
    'adriana.romero2@outlook.com',
    '$2b$10$iKVYW7.KvqA0hyC5nSa48.3WOBQn7BrkNYC3DgsiNknuymFaKAAY2',
    'Adriana',
    'Romero',
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    (SELECT id FROM "Roles" WHERE "name" = 'Cliente' LIMIT 1)
  ),
  (
    gen_random_uuid()::text,
    'manuel.espinoza3@hotmail.com',
    '$2b$10$iKVYW7.KvqA0hyC5nSa48.3WOBQn7BrkNYC3DgsiNknuymFaKAAY2',
    'Manuel',
    'Espinoza',
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    (SELECT id FROM "Roles" WHERE "name" = 'Cliente' LIMIT 1)
  ),
  (
    gen_random_uuid()::text,
    'carlos.munoz4@gmail.com',
    '$2b$10$iKVYW7.KvqA0hyC5nSa48.3WOBQn7BrkNYC3DgsiNknuymFaKAAY2',
    'Carlos',
    'Muñoz',
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    (SELECT id FROM "Roles" WHERE "name" = 'Cliente' LIMIT 1)
  ),
  (
    gen_random_uuid()::text,
    'mariana.sandoval5@outlook.com',
    '$2b$10$iKVYW7.KvqA0hyC5nSa48.3WOBQn7BrkNYC3DgsiNknuymFaKAAY2',
    'Mariana',
    'Sandoval',
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    (SELECT id FROM "Roles" WHERE "name" = 'Cliente' LIMIT 1)
  ),
  (
    gen_random_uuid()::text,
    'jose.herrera6@hotmail.com',
    '$2b$10$iKVYW7.KvqA0hyC5nSa48.3WOBQn7BrkNYC3DgsiNknuymFaKAAY2',
    'José',
    'Herrera',
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    (SELECT id FROM "Roles" WHERE "name" = 'Cliente' LIMIT 1)
  ),
  (
    gen_random_uuid()::text,
    'daniel.mendoza7@gmail.com',
    '$2b$10$iKVYW7.KvqA0hyC5nSa48.3WOBQn7BrkNYC3DgsiNknuymFaKAAY2',
    'Daniel',
    'Mendoza',
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    (SELECT id FROM "Roles" WHERE "name" = 'Cliente' LIMIT 1)
  ),
  (
    gen_random_uuid()::text,
    'daniela.nunez8@outlook.com',
    '$2b$10$iKVYW7.KvqA0hyC5nSa48.3WOBQn7BrkNYC3DgsiNknuymFaKAAY2',
    'Daniela',
    'Núñez',
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    (SELECT id FROM "Roles" WHERE "name" = 'Cliente' LIMIT 1)
  ),
  (
    gen_random_uuid()::text,
    'hugo.ruiz9@hotmail.com',
    '$2b$10$iKVYW7.KvqA0hyC5nSa48.3WOBQn7BrkNYC3DgsiNknuymFaKAAY2',
    'Hugo',
    'Ruiz',
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    (SELECT id FROM "Roles" WHERE "name" = 'Cliente' LIMIT 1)
  ),
  (
    gen_random_uuid()::text,
    'mariana.mendez10@gmail.com',
    '$2b$10$iKVYW7.KvqA0hyC5nSa48.3WOBQn7BrkNYC3DgsiNknuymFaKAAY2',
    'Mariana',
    'Méndez',
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    (SELECT id FROM "Roles" WHERE "name" = 'Cliente' LIMIT 1)
  ),
  (
    gen_random_uuid()::text,
    'carolina.espinoza11@gmail.com',
    '$2b$10$iKVYW7.KvqA0hyC5nSa48.3WOBQn7BrkNYC3DgsiNknuymFaKAAY2',
    'Carolina',
    'Espinoza',
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    (SELECT id FROM "Roles" WHERE "name" = 'Cliente' LIMIT 1)
  ),
  (
    gen_random_uuid()::text,
    'martin.espinoza12@gmail.com',
    '$2b$10$iKVYW7.KvqA0hyC5nSa48.3WOBQn7BrkNYC3DgsiNknuymFaKAAY2',
    'Martín',
    'Espinoza',
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    (SELECT id FROM "Roles" WHERE "name" = 'Cliente' LIMIT 1)
  ),
  (
    gen_random_uuid()::text,
    'maria.gonzalez13@gmail.com',
    '$2b$10$iKVYW7.KvqA0hyC5nSa48.3WOBQn7BrkNYC3DgsiNknuymFaKAAY2',
    'María',
    'González',
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    (SELECT id FROM "Roles" WHERE "name" = 'Cliente' LIMIT 1)
  ),
  (
    gen_random_uuid()::text,
    'francisco.ruiz14@outlook.com',
    '$2b$10$iKVYW7.KvqA0hyC5nSa48.3WOBQn7BrkNYC3DgsiNknuymFaKAAY2',
    'Francisco',
    'Ruiz',
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    (SELECT id FROM "Roles" WHERE "name" = 'Cliente' LIMIT 1)
  ),
  (
    gen_random_uuid()::text,
    'luis.gonzalez15@outlook.com',
    '$2b$10$iKVYW7.KvqA0hyC5nSa48.3WOBQn7BrkNYC3DgsiNknuymFaKAAY2',
    'Luis',
    'González',
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    (SELECT id FROM "Roles" WHERE "name" = 'Cliente' LIMIT 1)
  ),
  (
    gen_random_uuid()::text,
    'pedro.nunez16@gmail.com',
    '$2b$10$iKVYW7.KvqA0hyC5nSa48.3WOBQn7BrkNYC3DgsiNknuymFaKAAY2',
    'Pedro',
    'Núñez',
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    (SELECT id FROM "Roles" WHERE "name" = 'Cliente' LIMIT 1)
  ),
  (
    gen_random_uuid()::text,
    'pedro.sanchez17@outlook.com',
    '$2b$10$iKVYW7.KvqA0hyC5nSa48.3WOBQn7BrkNYC3DgsiNknuymFaKAAY2',
    'Pedro',
    'Sánchez',
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    (SELECT id FROM "Roles" WHERE "name" = 'Cliente' LIMIT 1)
  ),
  (
    gen_random_uuid()::text,
    'isabel.salazar18@outlook.com',
    '$2b$10$iKVYW7.KvqA0hyC5nSa48.3WOBQn7BrkNYC3DgsiNknuymFaKAAY2',
    'Isabel',
    'Salazar',
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    (SELECT id FROM "Roles" WHERE "name" = 'Cliente' LIMIT 1)
  ),
  (
    gen_random_uuid()::text,
    'carolina.torres19@hotmail.com',
    '$2b$10$iKVYW7.KvqA0hyC5nSa48.3WOBQn7BrkNYC3DgsiNknuymFaKAAY2',
    'Carolina',
    'Torres',
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    (SELECT id FROM "Roles" WHERE "name" = 'Cliente' LIMIT 1)
  ),
  (
    gen_random_uuid()::text,
    'mariana.castro20@outlook.com',
    '$2b$10$iKVYW7.KvqA0hyC5nSa48.3WOBQn7BrkNYC3DgsiNknuymFaKAAY2',
    'Mariana',
    'Castro',
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    (SELECT id FROM "Roles" WHERE "name" = 'Cliente' LIMIT 1)
  ),
  (
    gen_random_uuid()::text,
    'francisco.ortiz21@hotmail.com',
    '$2b$10$iKVYW7.KvqA0hyC5nSa48.3WOBQn7BrkNYC3DgsiNknuymFaKAAY2',
    'Francisco',
    'Ortiz',
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    (SELECT id FROM "Roles" WHERE "name" = 'Cliente' LIMIT 1)
  ),
  (
    gen_random_uuid()::text,
    'daniela.rivera22@gmail.com',
    '$2b$10$iKVYW7.KvqA0hyC5nSa48.3WOBQn7BrkNYC3DgsiNknuymFaKAAY2',
    'Daniela',
    'Rivera',
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    (SELECT id FROM "Roles" WHERE "name" = 'Cliente' LIMIT 1)
  ),
  (
    gen_random_uuid()::text,
    'javier.salazar23@outlook.com',
    '$2b$10$iKVYW7.KvqA0hyC5nSa48.3WOBQn7BrkNYC3DgsiNknuymFaKAAY2',
    'Javier',
    'Salazar',
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    (SELECT id FROM "Roles" WHERE "name" = 'Cliente' LIMIT 1)
  ),
  (
    gen_random_uuid()::text,
    'gabriela.estrada24@hotmail.com',
    '$2b$10$iKVYW7.KvqA0hyC5nSa48.3WOBQn7BrkNYC3DgsiNknuymFaKAAY2',
    'Gabriela',
    'Estrada',
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    (SELECT id FROM "Roles" WHERE "name" = 'Cliente' LIMIT 1)
  ),
  (
    gen_random_uuid()::text,
    'gabriela.moreno25@hotmail.com',
    '$2b$10$iKVYW7.KvqA0hyC5nSa48.3WOBQn7BrkNYC3DgsiNknuymFaKAAY2',
    'Gabriela',
    'Moreno',
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    (SELECT id FROM "Roles" WHERE "name" = 'Cliente' LIMIT 1)
  ),
  (
    gen_random_uuid()::text,
    'gabriel.mendez26@outlook.com',
    '$2b$10$iKVYW7.KvqA0hyC5nSa48.3WOBQn7BrkNYC3DgsiNknuymFaKAAY2',
    'Gabriel',
    'Méndez',
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    (SELECT id FROM "Roles" WHERE "name" = 'Cliente' LIMIT 1)
  ),
  (
    gen_random_uuid()::text,
    'carmen.gomez27@hotmail.com',
    '$2b$10$iKVYW7.KvqA0hyC5nSa48.3WOBQn7BrkNYC3DgsiNknuymFaKAAY2',
    'Carmen',
    'Gómez',
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    (SELECT id FROM "Roles" WHERE "name" = 'Cliente' LIMIT 1)
  ),
  (
    gen_random_uuid()::text,
    'oscar.herrera28@gmail.com',
    '$2b$10$iKVYW7.KvqA0hyC5nSa48.3WOBQn7BrkNYC3DgsiNknuymFaKAAY2',
    'Óscar',
    'Herrera',
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    (SELECT id FROM "Roles" WHERE "name" = 'Cliente' LIMIT 1)
  ),
  (
    gen_random_uuid()::text,
    'rosa.gonzalez29@outlook.com',
    '$2b$10$iKVYW7.KvqA0hyC5nSa48.3WOBQn7BrkNYC3DgsiNknuymFaKAAY2',
    'Rosa',
    'González',
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    (SELECT id FROM "Roles" WHERE "name" = 'Cliente' LIMIT 1)
  ),
  (
    gen_random_uuid()::text,
    'lucia.guerrero30@outlook.com',
    '$2b$10$iKVYW7.KvqA0hyC5nSa48.3WOBQn7BrkNYC3DgsiNknuymFaKAAY2',
    'Lucía',
    'Guerrero',
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    (SELECT id FROM "Roles" WHERE "name" = 'Cliente' LIMIT 1)
  ),
  (
    gen_random_uuid()::text,
    'maria.chavez31@hotmail.com',
    '$2b$10$iKVYW7.KvqA0hyC5nSa48.3WOBQn7BrkNYC3DgsiNknuymFaKAAY2',
    'María',
    'Chávez',
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    (SELECT id FROM "Roles" WHERE "name" = 'Cliente' LIMIT 1)
  ),
  (
    gen_random_uuid()::text,
    'daniela.romero32@gmail.com',
    '$2b$10$iKVYW7.KvqA0hyC5nSa48.3WOBQn7BrkNYC3DgsiNknuymFaKAAY2',
    'Daniela',
    'Romero',
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    (SELECT id FROM "Roles" WHERE "name" = 'Cliente' LIMIT 1)
  ),
  (
    gen_random_uuid()::text,
    'camila.diaz33@outlook.com',
    '$2b$10$iKVYW7.KvqA0hyC5nSa48.3WOBQn7BrkNYC3DgsiNknuymFaKAAY2',
    'Camila',
    'Díaz',
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    (SELECT id FROM "Roles" WHERE "name" = 'Cliente' LIMIT 1)
  ),
  (
    gen_random_uuid()::text,
    'luz.maldonado34@hotmail.com',
    '$2b$10$iKVYW7.KvqA0hyC5nSa48.3WOBQn7BrkNYC3DgsiNknuymFaKAAY2',
    'Luz',
    'Maldonado',
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    (SELECT id FROM "Roles" WHERE "name" = 'Cliente' LIMIT 1)
  ),
  (
    gen_random_uuid()::text,
    'lucia.martinez35@outlook.com',
    '$2b$10$iKVYW7.KvqA0hyC5nSa48.3WOBQn7BrkNYC3DgsiNknuymFaKAAY2',
    'Lucía',
    'Martínez',
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    (SELECT id FROM "Roles" WHERE "name" = 'Cliente' LIMIT 1)
  ),
  (
    gen_random_uuid()::text,
    'carmen.morales36@gmail.com',
    '$2b$10$iKVYW7.KvqA0hyC5nSa48.3WOBQn7BrkNYC3DgsiNknuymFaKAAY2',
    'Carmen',
    'Morales',
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    (SELECT id FROM "Roles" WHERE "name" = 'Cliente' LIMIT 1)
  ),
  (
    gen_random_uuid()::text,
    'daniel.marin37@gmail.com',
    '$2b$10$iKVYW7.KvqA0hyC5nSa48.3WOBQn7BrkNYC3DgsiNknuymFaKAAY2',
    'Daniel',
    'Marín',
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    (SELECT id FROM "Roles" WHERE "name" = 'Cliente' LIMIT 1)
  ),
  (
    gen_random_uuid()::text,
    'carolina.mendez38@hotmail.com',
    '$2b$10$iKVYW7.KvqA0hyC5nSa48.3WOBQn7BrkNYC3DgsiNknuymFaKAAY2',
    'Carolina',
    'Méndez',
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    (SELECT id FROM "Roles" WHERE "name" = 'Cliente' LIMIT 1)
  ),
  (
    gen_random_uuid()::text,
    'lucia.castillo39@hotmail.com',
    '$2b$10$iKVYW7.KvqA0hyC5nSa48.3WOBQn7BrkNYC3DgsiNknuymFaKAAY2',
    'Lucía',
    'Castillo',
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    (SELECT id FROM "Roles" WHERE "name" = 'Cliente' LIMIT 1)
  ),
  (
    gen_random_uuid()::text,
    'jose.rios40@outlook.com',
    '$2b$10$iKVYW7.KvqA0hyC5nSa48.3WOBQn7BrkNYC3DgsiNknuymFaKAAY2',
    'José',
    'Ríos',
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    (SELECT id FROM "Roles" WHERE "name" = 'Cliente' LIMIT 1)
  ),
  (
    gen_random_uuid()::text,
    'carlos.castro41@gmail.com',
    '$2b$10$iKVYW7.KvqA0hyC5nSa48.3WOBQn7BrkNYC3DgsiNknuymFaKAAY2',
    'Carlos',
    'Castro',
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    (SELECT id FROM "Roles" WHERE "name" = 'Cliente' LIMIT 1)
  ),
  (
    gen_random_uuid()::text,
    'pedro.alvarez42@hotmail.com',
    '$2b$10$iKVYW7.KvqA0hyC5nSa48.3WOBQn7BrkNYC3DgsiNknuymFaKAAY2',
    'Pedro',
    'Álvarez',
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    (SELECT id FROM "Roles" WHERE "name" = 'Cliente' LIMIT 1)
  ),
  (
    gen_random_uuid()::text,
    'samuel.diaz43@hotmail.com',
    '$2b$10$iKVYW7.KvqA0hyC5nSa48.3WOBQn7BrkNYC3DgsiNknuymFaKAAY2',
    'Samuel',
    'Díaz',
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    (SELECT id FROM "Roles" WHERE "name" = 'Cliente' LIMIT 1)
  ),
  (
    gen_random_uuid()::text,
    'juan.aguilar44@hotmail.com',
    '$2b$10$iKVYW7.KvqA0hyC5nSa48.3WOBQn7BrkNYC3DgsiNknuymFaKAAY2',
    'Juan',
    'Aguilar',
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    (SELECT id FROM "Roles" WHERE "name" = 'Cliente' LIMIT 1)
  ),
  (
    gen_random_uuid()::text,
    'carolina.perez45@hotmail.com',
    '$2b$10$iKVYW7.KvqA0hyC5nSa48.3WOBQn7BrkNYC3DgsiNknuymFaKAAY2',
    'Carolina',
    'Pérez',
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    (SELECT id FROM "Roles" WHERE "name" = 'Cliente' LIMIT 1)
  ),
  (
    gen_random_uuid()::text,
    'maria.rodriguez46@gmail.com',
    '$2b$10$iKVYW7.KvqA0hyC5nSa48.3WOBQn7BrkNYC3DgsiNknuymFaKAAY2',
    'María',
    'Rodríguez',
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    (SELECT id FROM "Roles" WHERE "name" = 'Cliente' LIMIT 1)
  ),
  (
    gen_random_uuid()::text,
    'jose.marin47@hotmail.com',
    '$2b$10$iKVYW7.KvqA0hyC5nSa48.3WOBQn7BrkNYC3DgsiNknuymFaKAAY2',
    'José',
    'Marín',
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    (SELECT id FROM "Roles" WHERE "name" = 'Cliente' LIMIT 1)
  ),
  (
    gen_random_uuid()::text,
    'pedro.romero48@gmail.com',
    '$2b$10$iKVYW7.KvqA0hyC5nSa48.3WOBQn7BrkNYC3DgsiNknuymFaKAAY2',
    'Pedro',
    'Romero',
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    (SELECT id FROM "Roles" WHERE "name" = 'Cliente' LIMIT 1)
  ),
  (
    gen_random_uuid()::text,
    'isabel.perez49@hotmail.com',
    '$2b$10$iKVYW7.KvqA0hyC5nSa48.3WOBQn7BrkNYC3DgsiNknuymFaKAAY2',
    'Isabel',
    'Pérez',
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    (SELECT id FROM "Roles" WHERE "name" = 'Cliente' LIMIT 1)
  ),
  (
    gen_random_uuid()::text,
    'gabriel.rodriguez50@hotmail.com',
    '$2b$10$iKVYW7.KvqA0hyC5nSa48.3WOBQn7BrkNYC3DgsiNknuymFaKAAY2',
    'Gabriel',
    'Rodríguez',
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    (SELECT id FROM "Roles" WHERE "name" = 'Cliente' LIMIT 1)
  )
ON CONFLICT ("email") DO NOTHING;
