### Variables
@baseUrl = http://localhost:3000/roles

### Crear Rol (Administrador)
# @name crearRol
POST {{baseUrl}}
Content-Type: application/json

{
   "name": "Administrador",
   "description": "Rol con todos los accesos",
   "active": true
}

### Crear Rol (Cliente)
POST {{baseUrl}}
Content-Type: application/json

{
   "name": "Manager 2",
   "description": "Rol secundario",
   "active": true
}

### Listar todos los roles
GET {{baseUrl}}

### Obtener Rol por ID
# Reemplaza el ID por uno generado
@rolId = {{crearRol.response.body.id}}
GET {{baseUrl}}/{{rolId}}

### Actualizar Rol
PUT {{baseUrl}}/{{rolId}}
Content-Type: application/json

{
   "name": "Super Administrador",
   "description": "Rol con control total",
   "active": true
}

### Eliminar Rol
DELETE {{baseUrl}}/{{rolId}}
