### Variables
@baseUrl = http://localhost:3000/roles

### Crear Rol (Administrador)
POST {{baseUrl}}
Content-Type: application/json

{
   "name": "Administrador",
   "description": "Rol con todos los accesos"
}

### Crear Rol (Cliente)
POST {{baseUrl}}
Content-Type: application/json

{
   "name": "Nuevo Rol",
   "description": "Rol secundario"
}

### Listar todos los roles
GET {{baseUrl}}

@roleIdAdm = def3ab03-6e1f-4483-b76c-e4b02a429bc9
@roleIdNew = 7bd4de1a-8ced-4e04-a067-59ece53af49d

### Obtener Rol por ID (Administrador)
GET {{baseUrl}}/{{roleIdAdm}}

### Busqueda con filtros
GET {{baseUrl}}/search?skip=q&take=3&search=Admin

### Actualizar Rol
PUT {{baseUrl}}
Content-Type: application/json

{
   "id": "{{roleIdNew}}",
   "name": "Nuevo Rol Editado",
   "description": "Nuevo Rol Editado"
}

### Eliminar Rol
DELETE {{baseUrl}}/{{roleIdNew}}
