### Variables
@baseUrl = http://localhost:3000/roles

### Crear Rol (Administrador)
POST {{baseUrl}}
Content-Type: application/json

{
   "name": "Administrador",
   "description": "Rol con todos los accesos"
}

### Crear Rol (Cliente)
POST {{baseUrl}}
Content-Type: application/json

{
   "name": "Nuevo Rol",
   "description": "Rol secundario"
}

### Listar todos los roles
GET {{baseUrl}}

@roleIdAdm = 2597f9c2-f1c5-41d8-84fb-a2566e3f3952
@roleIdNew = de49e74c-82a0-4a90-8339-e577269e3509

### Obtener Rol por ID (Administrador)
GET {{baseUrl}}/{{roleIdAdm}}

### Busqueda con filtros
GET {{baseUrl}}/search?skip=0&take=3&search=Admin

### Actualizar Rol
PUT {{baseUrl}}
Content-Type: application/json

{
   "id": "{{roleIdNew}}",
   "name": "Nuevo Rol Editado",
   "description": "Nuevo Rol Editado"
}

### Eliminar Rol
DELETE {{baseUrl}}/{{roleIdNew}}
