### Variables
@baseUrl = http://localhost:3000

### Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
   "email": "root@admin.com",
   "password": "Admin*123"
}

### Refrescar Token
POST {{baseUrl}}/auth/refrescar-token
Content-Type: application/json

### Crear Cuenta Usuario
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
   "email": "dubian26@gmail.com",
   "password": "Pruebas*1",
   "firstName": "Dubian",
   "lastName": "Sepulveda"
}

### Listar Usuarios
GET {{baseUrl}}/usuarios

### Buscar Usuario por Id
GET {{baseUrl}}/usuarios/019cef77ac8677efb5f02cbe529f3374

### Buscar Usuario por Email
GET {{baseUrl}}/usuarios/email/dubian26@gmail.com

### Actualizar Usuario
PUT {{baseUrl}}/usuarios/019cef77ac8677efb5f02cbe529f3374
Content-Type: application/json

{
   "nombres": "Juan Actualizado",
   "apellidos": "Perez Actualizado"
}

### Inactivar Usuario
PUT {{baseUrl}}/usuarios/019cef77ac8677efb5f02cbe529f3374/inactivar

### Eliminar Usuario
DELETE {{baseUrl}}/usuarios/019cf83a7882728eafebd0b9e839a675
